### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by TheEvilSocks** [OpenMods/OpenPeripheral-Addons#45] opened 2015-01-20 14:15 UTC
I'm getting the following crash when connecting a Proxy at a wired network using cables.
The proxy is aimed at a Diamond Chest from the Iron Chests mod.
```
Time: 20/01/15 15:06
Description: Ticking block entity

java.lang.NoSuchMethodError: dan200.computercraft.api.peripheral.IComputerAccess.mount(Ljava/lang/String;Ldan200/computercraft/api/filesystem/IMount;Ljava/lang/String;)Ljava/lang/String;
	at dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper.mount(TileCable.java:933)
	at openperipheral.adapter.peripheral.AdapterPeripheral.attach(AdapterPeripheral.java:77)
	at openperipheral.addons.peripheralproxy.WrappedPeripheral.attach(WrappedPeripheral.java:33)
	at dan200.computercraft.shared.peripheral.modem.TileCable$RemotePeripheralWrapper.attach(TileCable.java:898)
	at dan200.computercraft.shared.peripheral.modem.TileCable.attachPeripheral(TileCable.java:733)
	at dan200.computercraft.shared.peripheral.modem.TileCable.findPeripherals(TileCable.java:1030)
	at dan200.computercraft.shared.peripheral.modem.TileCable.func_145845_h(TileCable.java:657)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Full crash report: http://pastebin.com/QNy7dMJ5

**Comment by TBotV63** [comment] 2015-01-20 14:18
Looks like a ComputerCraft issue...

**Comment by SinZ163** [comment] 2015-01-20 14:20
Update ProjectRed, duplicate of #42

**Closed by SinZ163** 2015-01-20 14:20 UTC

**Comment by boq** [comment] 2015-01-20 15:48
Actually, duplicate of OpenMods/OpenPeripheral#206, OpenMods/OpenPeripheral#207, OpenMods/OpenPeripheral#217, OpenMods/OpenPeripheral#221, #40, #42 and OpenMods/OpenPeripheral-Integration#1.
