### ISSUE TITLE
Terminal Glasses Bridge: glasses.addText() returns string insted of the displayes object.

### ISSUE THREAD

**Issue by kla-sch** [OpenMods/OpenPeripheral-Addons#49] opened 2015-01-28 19:18 UTC
I am using DW20 1.0.3 which claims to use 0.2.0-snapshot-139.
The glasses.addText()  of terminal glasses bridge returns a string instead of the displayed object.
The string contains something like "openperipheral.adapter.object.LuaObjectWrapper$WrappedLuaObject@2d86d251"
It worked in DW20 1.0.2 (OPA 0.2.0-snapshot-122).

**Comment by boq** [comment] 2015-01-28 19:22
Guess what? Ancient version (same as #48). And duplicate of #41

**Closed by boq** 2015-01-28 19:22 UTC
